### ISSUE TITLE
Typing <ENTER> with any value causes an exception

### ISSUE THREAD

**Issue by dsoon** [dsoon/PS2#7]
1> DECLARE I : INTEGER
2> INPUT I
3> .

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    PS2.runPrompt()
  File "/home/runner/PS2/ps2/app.py", line 51, in runPrompt
    PS2.run("".join(prog))
  File "/home/runner/PS2/ps2/app.py", line 87, in run
    Interpretor(statements).interpret()
  File "/home/runner/PS2/ps2/interpret/interpretor.py", line 15, in interpret
    stmt.interpret()
  File "/home/runner/PS2/ps2/statement/statement.py", line 276, in interpret
    symbol.value = int(value)
ValueError: invalid literal for int() with base 10: ''
>

**Comment by dsoon** [comment]
Issue fixed: A runtime exception will occur if data conversion on INPUT to correct data type cannot be done
